### ISSUE TITLE
How do I use this application from Command line

### ISSUE THREAD

**Issue by bhargavweb** [bdsatish/drik-panchanga#6]
How do I use this from command line?

**Comment by bdsatish** [comment]
There is no interactive CLI if that is what you meant. However, you can run it from Python. Quick and dirty example:

```python
from panchanga import *

place = Place(12.972, 77.594, +5.5)     # Latitude, Longitude, time zone of your place
date = gregorian_to_jd(Date(2009, 7, 15))    # YYYY-MM-DD you want to convert
print(tithi(date, place))            #That's all
```

**Comment by bhargavweb** [comment]
Thanks for the help Satish :+1: . I've gone through the source and figured it out. 
I was new to python couple of days back. Learnt python while reviewing your code.
