### ISSUE TITLE
bug in tithi() function when tithi is to be skipped

### ISSUE THREAD

**Issue by dmranade** [bdsatish/drik-panchanga#8]
def tithi(jd, place):
    ....
    5. check for skipped tithi
    isSkipped - ...
    if isSkipped:
        ...
        answer += [int(leap_tithi), to_dms(ends)]
-------------------
The last line above results in a 4 element list instead of the expected two element list.
e.g.
okay: [21, [22, 23, 21]]
bad : [2, [8, 59. 1], 3, [29, 55, 2]]
To fix:
change last line to 
        answer = [int(leap_tithi), to_dms(ends)]

**Comment by bdsatish** [comment]
It's not a bug, it is intentional. In the four-element list:

```
 [2, [8, 59. 1], 3, [29, 55, 2]]
```

the first two elements refer to the *first* tithi of today (2 = dvitiya tithi) and the next two elements refer to the *second* tithi (aka skipped tithi) of today (3 = tritiya tithi). Both tithis occur in the given JD.

**Comment by dmranade** [comment]
oh, I see. 
Caller of tithi must be ready to get either a 2 or 4 len list.

closing the issue.
